### ISSUE TITLE
TS2322: Type 'BullMQAdapter' is not assignable to type 'BaseAdapter' (Wrong Types)

### ISSUE THREAD

**Issue by AlexZeDim** [felixmosh/bull-board#271]
Hi!

I got almost the same issue, as it was mentioned a while ago in this report #253. Unless old things don't help me.

**Node.js: 16.1**

`package.json`

```
  "dependencies": {
    "@anchan828/nest-bullmq": "^0.5.20",
    "@nestjs/common": "^7.6.15",
    "@nestjs/core": "^7.6.15",
    "@nestjs/mongoose": "^7.2.4",
    "@nestjs/platform-express": "^7.6.15",
    "@nestjs/schedule": "^0.4.3",
    "@nestjs/swagger": "^4.8.0",
    "@types/cheerio": "^0.22.28",
    "bullmq": "^1.15.1",
    "rimraf": "^3.0.2",
  },
  "devDependencies": {
    "@nestjs/cli": "^7.6.0",
    "@nestjs/schematics": "^7.3.0",
    "@nestjs/testing": "^7.6.15",
    "@types/bull-board": "^0.6.0",
    "@types/config": "^0.0.38",
    "@types/cron": "^1.7.2",
    "@types/express": "^4.17.11",
    "@types/ioredis": "^4.26.1",
    "@types/jest": "^26.0.22",
    "@types/lodash": "^4.14.168",
    "@types/node": "^14.14.36",
    "bull-board": "^2.0.2",
    "ts-loader": "^8.0.18",
    "ts-node": "^9.1.1",
    "tsconfig-paths": "^3.9.0",
    "typescript": "^4.2.3",
    "webpack": "^5.36.2"
  }
```

As you may see, I am using `bull-board` with `nestjs`. Here is a code image with error description:
![image](https://user-images.githubusercontent.com/907696/117508359-1ad1ae00-af91-11eb-91ad-445a0864f769.png)

Part of `tsconfig.json` responsible for `imports`:

```
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "target": "es2017",
    "sourceMap": true,
```

And my `IORedis tree`

```
+-- @types/bull-board@0.6.0
| `-- @types/bull@3.15.1
|   `-- @types/ioredis@4.26.1 deduped
+-- @types/ioredis@4.26.1
+-- bull-board@2.0.2
| `-- @types/ioredis@4.26.1 deduped
`-- bullmq@1.24.4
  `-- @types/ioredis@4.26.1 deduped
```

## What have I done:

Of course, I have tried various things, like declaring variables with queues outside the `createBullBoard` part, downgrading (which helps), and so on.

But the funniest thing is, that actually `bull-board` is working fine, if I prefer to ignore errors manually via `// @ts-ignore` comments. So it's problem with interfaces, not with workability. But it is challengings to use bull-board in production.

**Comment by AlexZeDim** [comment]
After some investigation I have checked that the problem was created by the following string `abstract getClient(): Promise<Redis.Redis>;` in `bull-board\dist\queueAdapters\base.d.ts` file.

I removed `.Redis` and the result string:15 in method `getClient()` with: `abstract getClient(): Promise<Redis>;` gives me no error at last. 

If so, a pull request with this change is comings.

**Comment by felixmosh** [comment]
Thank you @AlexZeDim ... But seems that your fix failing on CI.

Try to remove @types/bull-board from your project since we ship the lib with built in types

**Comment by AlexZeDim** [comment]
> Try to remove @types/bull-board from your project since we ship the lib with built-in types

I have tried with and without it. Unfortunately, it doesn't help. As for the fix, I modify the compiled dist folder in my own form (not this PR) that's why I don't receive any errors from TS.

For example <Redis> only: 

![image](https://user-images.githubusercontent.com/907696/117538246-f667e700-b00d-11eb-9495-e96d8f8d30f2.png)

And `<Redis.Redis>`

![image](https://user-images.githubusercontent.com/907696/117538268-126b8880-b00e-11eb-9d6d-41ac4786b3ad.png)

**Comment by felixmosh** [comment]
It is a confusion of types... not related to this lib.

can you try a fresh install? (removing `node_modules` & `package.lock`/`yarn.lock`)?

**Comment by AlexZeDim** [comment]
Already done it too with `yarn` and `npm` with and without docker build. The problem related with `BullMQAdapter` and `BaseAdapter` class and their `getClient()`.

**Comment by felixmosh** [comment]
Thank you for reporting this issue, I was able to reproduce the issue update updating types to latest 🙏🏼

**Comment by felixmosh** [comment]
Fix released at `v2.0.3`

**Comment by peon-root** [comment]
can we fix this for those on v1.*? It is still present in 1.7.2

**Comment by felixmosh** [comment]
Why do you not updating to v2?

The breaking changes are minor
